- hosts: localhost
  tasks:
  - name: import vars
    include_vars:
      dir: private

  - name: cask tasks
    include_tasks:
      file: tasks/casks.yml
      apply:
        tags:
          - casks
    tags: casks

  - name: tmux tasks
    include_tasks:
      file: tasks/tmux.yml
      apply:
        tags:
          - tmux
    tags: tmux

  - name: emacs tasks
    include_tasks:
      file: tasks/emacs.yml
      apply:
        tags:
          - emacs
    tags: emacs

  - name: zsh tasks
    include_tasks:
      file: tasks/zsh.yml
      apply:
        tags:
          - zsh
    tags: zsh

  - name: dotfiles tasks
    include_tasks:
      file: tasks/dotfiles.yml
      apply:
        tags:
          - dotfiles
    tags: dotfiles

