- name: install homeshick
  community.general.homebrew:
    path: /opt/homebrew/bin
    name: homeshick


- name: setup repos directory
  ansible.builtin.file:
    path: ~/.homesick/repos
    state: directory
    mode: '0755'

- name: clone dotfiles castle
  ansible.builtin.shell:
    cmd: homeshick clone https://github.com/codelahoma/dotfiles.git

- name: checkout m1 branch
  ansible.builtin.shell:
    chdir: ~/.homesick/repos/dotfiles
    cmd: git checkout m1

- name: link dotfiles castle
  ansible.builtin.shell:
    cmd: homeshick link dotfiles --force
