- name: install homeshick
  community.general.homebrew:
    path: /opt/homebrew/bin
    name: homeshick


- name: setup repos directory
  ansible.builtin.file:
    path: ~/.homesick/repos
    state: directory
    mode: '0755'

- name: check if dotfiles castle present
  stat:
    path: ~/.homesick/repos/dotfiles
  register: dotfiles_stats

- name: clone dotfiles castle if not there
  when: "not dotfiles_stats.stat.exists"
  block:
    - name: clone dotfiles castle
      ansible.builtin.git:
        repo: https://github.com/codelahoma/dotfiles.git
        dest: "~/.homesick/repos/dotfiles"
        version: "m1"


- name: link dotfiles castle
  ansible.builtin.shell:
    cmd: homeshick link dotfiles --force
