- name: tap emacs-plus cask
  community.general.homebrew_tap:
    path: /opt/homebrew/bin
    name: d12frosted/emacs-plus
- name: install emacs-plus
  community.general.homebrew:
    path: /opt/homebrew/bin
    name: emacs-plus


- name: install spacemacs
  ansible.builtin.git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

- name: checkout spacemacs develop branch
  ansible.builtin.shell:
    chdir: ~/.emacs.d
    cmd: git checkout develop
